
name: JoinTelegram
version: 1.4.4
main: dev.jointg.JoinTgPlugin
api-version: "${paper.plugin.api-version}"
authors:
  - alexcuadroo
softdepend:
  - LuckPerms
commands:
  jointg:
    description: "Recarga la configuración del plugin"
    usage: "/jointg reload"
    permission: "jointg.reload"
    permission-message: "No tienes permiso para usar este comando."
